### ISSUE TITLE
pickles.exe can't take path with spaces from cmd

### ISSUE THREAD

**Issue by Rain9333** [picklesdoc/docs#14]
You can't provide any path (output, feature or xml) if there is spaces in it. You also can't escape it but putting it in quotes like you usually do with running program from command prompt.

**Comment by dirkrombauts** [comment]
Hi,
Which operating system are you using?

**Comment by Rain9333** [comment]
Hey,
Windows 10, 64 bit.

**Comment by dirkrombauts** [comment]
Could you please create an issue for this on the [Pickles repository](https://github.com/picklesdoc/pickles)? Thanks!

**Comment by Rain9333** [comment]
Done -> https://github.com/picklesdoc/pickles/issues/429
Thanks

**Comment by dirkrombauts** [comment]
Thanks! I'm closing this issue.
