### ISSUE TITLE
Does Pickle only support SpecFlow+ Runner?

### ISSUE THREAD

**Issue by GreenbowAlabama** [picklesdoc/docs#23]
We're using the SpecFlow NUnit Runners.  Was curious if it supported test results with this runner.

**Comment by dirkrombauts** [comment]
Hi,
I'm not sure what you mean exactly by "SpecFlow NUnit Runners". Pickles can read the test results that are produced by NUnit when running SpecFlow scenarios. I hope this helps.

**Comment by GreenbowAlabama** [comment]
Thanks for the quick reply, sorry if I'm not wording this properly.  When I build and run, the documentation is spit out real nice.  However, in the overview tab, the only thing that shows is, for example, '6 Inconclusive Scenarios' with 0 pass/fail.  The documentation is being built at build time, so I'm not sure how it's able to snag the NUnit test results.  Maybe I'm missing a switch or setting?

**Comment by dirkrombauts** [comment]
How are you building the documentation? Could you post the command line, or a screen shot of the GUI? Feel free to redact names and such ...

**Comment by GreenbowAlabama** [comment]
It's being built automatically with Pickles.MSBuild.  Once I build my solution, it'll automatically update the \documentation folder.  I'm using the format dhtml which is working great by the way.

Here is what I added to the csproj file:

  <PropertyGroup>
    <Pickles_Generate>True</Pickles_Generate>
    <Pickles_DocumentationFormat>dhtml</Pickles_DocumentationFormat>
    <Pickles_OutputDirectory>..\path\documentation</Pickles_OutputDirectory>
    <Pickles_FeatureDirectory>..\path\rules</Pickles_FeatureDirectory>
  </PropertyGroup>

I apologize in advance if this isn't what you're referring to when you say GUI.  If you're referring to the report, let me know and I can submit that as well.

**Comment by dirkrombauts** [comment]
That is more or less what I meant ... but still difficult to diagnose like this.

Could you perhaps create a very reduced example? A project with one feature file with one passing scenario, configured like you have it in your real solution? It would help me greatly if I could reproduce your problem on my own machine.

**Comment by GreenbowAlabama** [comment]
After reading your comments, I believe I'm missing something outside of Pickle itself.  I'm unable to point Pickle to a TestExecution.xml file because it's not being generated.  I think this is the key.  Correct me here if I'm on the wrong track but I'll keep researching on my end.

**Comment by GreenbowAlabama** [comment]
Just an update. It’s all working now, and it’s mainly due to your questions leading me in the right direction. The issue was I was under the impression NUnit was outputting an xml by default and I couldn’t find it. But after some research I figured out you have to use the console runner to output the xml and then use the console in pickles to read that xml output.

Here is what I am hoping works. And I think it’s mainly on the NUnit side but partially a Pickles question. NUnit question is mainly, can it be configured to always build that xml output from test explorer in visual studio? I know that’s mainly for me to figure out, not you.

If this is possible above, can Pickles be configured to build the documentation post run time instead of pre run time after configuring Pickles to point at the output xml from NUnit.
