### ISSUE TITLE
"Integrating Test Results From SpecRun" guide appears to have missing parts

### ISSUE THREAD

**Issue by ghost** [picklesdoc/docs#8]
This page appears to have a missing code block at this point:
- Still in ReportTemplate.cshtml, add this fragment before the closing /body element:

The missing code is commented out in the page source however editing and adding it to the report file causes an exception.

Is there a way to make the SpecRun integration work?

**Comment by dirkrombauts** [comment]
I'll take a look at it later today.

It has to be a problem of the documentation because I managed to get it working ;-)

**Comment by dirkrombauts** [comment]
Hi,

Here's a quick fix to get you on your way: have a look at https://raw.githubusercontent.com/picklesdoc/docs/master/docs/IntegratingTestResultsFromSpecRun.md - that shows the instructions in plain text.  Please let me know if you have any questions about them.

There appears to be a formatting problem on both github and the website. I'll look into that further.

**Comment by dirkrombauts** [comment]
And now it's shown on both github and the docs site.

I'm closing the issue, but let me know if you need further help with getting the results from specrun!
